spring:
  application:
    name: PingwitDentalManager

  datasource:
    url: jdbc:postgresql://localhost:5432/pingwit_dental_manager
    username: postgres
    password: docker2000

  liquibase:
    change-log: classpath:db.changelog/changelogmaster.xml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 7788

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework: DEBUG
      hibernate: DEBUG

decorator:
  datasource:
    datasource-proxy:
      logging: slf4j
      query:
        enable-logging: true
        log-level: info
      multiline: true
      format-sql: true

springdoc:
  api-docs:
    path: /api-docs
  packagesToScan: pl.pingwit.dentalmanager.controller
  swagger-ui:
    tryItOutEnabled: true
